#### Cloudformation template for creating s3 bucket, cloudfront distribution to host a static website

AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for s3 bucket and cloudfront distribution

Parameters:
  MyBucketName:
    Type: String
    Default: my-test-bk01
    
Resources:
 
  s3bucket:
    Type: AWS::S3::Bucket
    Description: Creating Amazon S3 bucket from CloudFormation
    Properties:
      BucketName: !Ref MyBucketName

#### Create OAC for cloudfront to access s3 bucket with an identity.      

  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Description: "origin access control(OAC) for allowing cloudfront to access S3 bucket"
        Name: static-hosting-OAC
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  cloudfrontdst:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig: 
        Origins:
          - DomainName: !Sub "${s3bucket}.s3.ap-south-1.amazonaws.com"
            Id: static-hosting
            S3OriginConfig:
              OriginAccessIdentity: ""
            OriginAccessControlId: !GetAtt CloudFrontOriginAccessControl.Id
        Enabled: "true"
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: static-hosting
          ForwardedValues:
            QueryString: "false"
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https

#### Implement bucket policy for cloudfront to access s3 bucket          

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref s3bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${s3bucket}/*"
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${cloudfrontdst}"

Outputs:
  s3bucketname: 
    Description: Bucket Created using this template.
    Value: !Ref s3bucket

      